# Set environments
default: &default
    server:
        host: auto
        port: 8080
        debug: true
        secretKey: development
        auth:
            username: dev
            password: dev
        theme: dark
        ssl:
            active: false
            cert: ./certs/cert.pem
            key: ./certs/key.pem
        owner:
            name: John Doe
            email: example@example.com
    logging:
        handlers: ["console"]
        level: "DEBUG"

    api:
        base: https://api.rawg.io/api/

development:
    <<: *default

production:
    <<: *default
    server:
        host: 127.0.0.1
        port: 443
        debug: false
        secretKey: auto
        auth:
            username: auto
            password: auto
        theme: light
        ssl:
            active: false
    logging:
        handlers: ["db"]
        level: "INFO"
        db:
            host: 127.0.0.1
            port: 5432
            name: logs

